# 1 - List the number of films per category.

SELECT 
    category.name AS category,
    COUNT(film.film_id) AS number_of_films
FROM
    category
        INNER JOIN
    film_category ON category.category_id = film_category.category_id
        INNER JOIN
    film ON film_category.film_id = film.film_id
GROUP BY category.name;

# 2 - Retrieve the store ID, city, and country for each store.

SELECT 
    store.store_id, address.city_id, country.country
FROM
    store
        INNER JOIN
    address ON store.address_id = address.address_id
        INNER JOIN
    city ON address.city_id = city.city_id
        INNER JOIN
    country ON city.country_id = country.country_id;


# 3 - Calculate the total revenue generated by each store in dollars.

SELECT 
    store.store_id, SUM(payment.amount)
FROM
    store
        INNER JOIN
    payment ON store.store_id = payment.staff_id
GROUP BY store_id;

# 4 - Determine the average running time of films for each category.

SELECT 
    category.name, AVG(film.length)
FROM
    film
        INNER JOIN
    category ON film.film_id = category.category_id
GROUP BY name;

# 5 - Identify the film categories with the longest average running time.

SELECT 
    category.name AS category,
    ROUND(AVG(film.length), 2) AS average_running_time
FROM
    category
        JOIN
    film_category ON category.category_id = film_category.category_id
        JOIN
    film ON film_category.film_id = film.film_id
GROUP BY category.name
ORDER BY average_running_time DESC;
 

# 6 - Display the top 10 most frequently rented movies in descending order.

SELECT 
    title, rental_rate
FROM
    film
ORDER BY rental_rate DESC
LIMIT 10;

# 7 - Determine if "Academy Dinosaur" can be rented from Store 1.

# 8 - Provide a list of all distinct film titles, along with their availability 
# status in the inventory. Include a column indicating whether each title is 
# 'Available' or 'NOT available.' Note that there are 42 titles that are not 
# in the inventory, and this information can be obtained using a CASE statement
# combined with IFNULL."

